import { AGENT_FILE_PATHS, type AgentId, SUPPORTED_AGENTS } from './generators.js'
import { GUIDANCE_VERSION, isGuidancePristine, parseGuidanceMarker } from './marker.js'

/** Drift state of a single generated guidance file. */
export type GuidanceFileState = 'current' | 'missing' | 'edited' | 'stale' | 'no-marker'

export interface AgentGuidanceStatus {
  agent: AgentId
  /** Path relative to the project root. */
  path: string
  state: GuidanceFileState
  reason: string
  /** Guidance version the current generator produces. */
  expectedVersion: number
  /** Version recorded in the file's marker (null when missing/unmarked). */
  markerVersion: number | null
  /** Content hash recorded in the file's marker (null when missing/unmarked). */
  markerHash: string | null
}

/**
 * Classifies a guidance file's drift state from its content (or `null` if it is
 * missing). Pure and deterministic — the caller reads the file; this decides.
 */
export function classifyGuidanceFile(agent: AgentId, content: string | null): AgentGuidanceStatus {
  const base = {
    agent,
    path: AGENT_FILE_PATHS[agent],
    expectedVersion: GUIDANCE_VERSION,
  }

  if (content === null) {
    return {
      ...base,
      state: 'missing',
      reason: 'File is missing.',
      markerVersion: null,
      markerHash: null,
    }
  }

  const marker = parseGuidanceMarker(content)
  if (!marker) {
    return {
      ...base,
      state: 'no-marker',
      reason: 'No TestPilot guidance marker — not a generated file.',
      markerVersion: null,
      markerHash: null,
    }
  }

  const shared = { markerVersion: marker.version, markerHash: marker.hash }

  if (!isGuidancePristine(content)) {
    return { ...base, ...shared, state: 'edited', reason: 'File was edited after generation.' }
  }
  if (marker.version !== GUIDANCE_VERSION) {
    return {
      ...base,
      ...shared,
      state: 'stale',
      reason: `Generated by guidance v${marker.version}; current is v${GUIDANCE_VERSION}.`,
    }
  }
  return { ...base, ...shared, state: 'current', reason: 'Up to date.' }
}

/** Returns the agents to check, in canonical order, given a selection (default: all). */
export function selectedAgents(agents?: readonly AgentId[]): AgentId[] {
  const set = new Set(agents ?? SUPPORTED_AGENTS)
  return SUPPORTED_AGENTS.filter((agent) => set.has(agent))
}
