/**
 * The single canonical TestPilot + Playwright guidance. Every agent file derives
 * from this one source, so there is no duplicated wall of text to keep in sync.
 *
 * Built as a line array so fenced code blocks (which contain backticks) are easy
 * to include. Keep it honest: do not describe features that do not exist yet.
 */
export const CANONICAL_GUIDANCE = [
  '## What TestPilot QA is',
  '',
  'TestPilot QA is a developer-experience toolkit on top of Playwright. It does **not** replace',
  'Playwright and is **not** a custom test runner — Playwright runs the tests. Keep this project as',
  'plain, ejectable Playwright.',
  '',
  '## Project structure',
  '',
  '- `tests/ui/` — UI tests (use `page` and user-facing locators)',
  '- `tests/api/` — API tests (use the `request` fixture)',
  '- `playwright.config.ts` — Playwright config (parallelism, projects, reporter)',
  '- `testpilot.config.ts` — TestPilot config (`testDir`, `playwrightConfig`, `suites`, rule severities)',
  '',
  '## Locator hierarchy (most → least preferred)',
  '',
  '1. `getByRole`, `getByLabel`, `getByPlaceholder`, `getByText`, `getByAltText`, `getByTitle`',
  '2. `getByTestId`',
  '3. Avoid raw CSS and `text=` engine strings',
  '4. Never use XPath, `:nth-child` / `.nth()`, class selectors, or deep `>` chains',
  '',
  '```ts',
  '// avoid',
  "page.locator('.btn-primary')",
  'page.locator(\'//button[@type="submit"]\')',
  '// prefer',
  "page.getByRole('button', { name: 'Save' })",
  "page.getByLabel('Email')",
  '```',
  '',
  '## Tags — how a subset gets run',
  '',
  'Tags are how a **cross-cutting** subset gets run — a smoke suite spans directories,',
  'so a path filter cannot express it. Path selection is still right for "just the UI',
  'tests" (`playwright test tests/ui`); the two are complementary.',
  '',
  'Before adding a test, check the vocabulary the project already uses',
  '(`testpilot tags`) and reuse it — **do not** invent a new tag when an existing one',
  'fits: a new tag is carried by your test alone, so no existing CI job runs it. If',
  'the project has no tags at all, do not start a vocabulary unprompted — ask first.',
  '',
  '```ts',
  '// a tag in the title, or in the details argument — Playwright reads both',
  "test('checkout works @smoke', async ({ page }) => { … })",
  "test('checkout works', { tag: ['@smoke'] }, async ({ page }) => { … })",
  '// a tag on a describe applies to every test inside it',
  "test.describe('billing @regression', () => { … })",
  '```',
  '',
  '- Tags start with `@` and contain no whitespace.',
  '- A tag must start with a letter, digit or `_` and contain no whitespace or a',
  '  second `@`. `.`, `-` and `:` are fine (`@team:auth`, `@P1.2`). Anything outside',
  '  that is a Playwright tag `testpilot run --tag` cannot select.',
  '- Put the `@` at the start of a word. `user@example.com` in a title is a tag to',
  '  Playwright, but `--tag` will not match it.',
  '- An untagged test still runs in the full suite, but is in no tagged subset —',
  '  so it silently misses the smoke and nightly runs people actually watch.',
  '- Run a subset with `testpilot run --tag smoke` (or `--suite <name>` for a set',
  "  named in `testpilot.config.ts`). It compiles to Playwright's own `--grep`.",
  '',
  '## Playwright best practices',
  '',
  '- Rely on Playwright auto-waiting; do **not** use `page.waitForTimeout()` (hard waits).',
  '- Use web-first assertions: `await expect(locator).toBeVisible()`, `toHaveText(...)`.',
  '- Keep tests independent and parallel-safe; avoid shared mutable state between tests.',
  '',
  '## API testing',
  '',
  '- Use the `request` fixture; assert `response.ok()` and the parsed body.',
  '- For offline examples, start a local `node:http` server inside the test.',
  '',
  '## Fixtures & Page Objects',
  '',
  '- Put reusable setup in Playwright fixtures; if the suite grows, put page interactions in Page',
  '  Objects (e.g. under `src/pages`).',
  '- Every test must be able to run on its own.',
  '',
  '## Use TestPilot',
  '',
  '- `testpilot analyze` — flag fragile locators and get a Locator Quality Score.',
  '- `testpilot tags` — list the tag vocabulary before adding or selecting tests.',
  '- `testpilot run --tag <tag>` — run a subset, without hand-writing a regex.',
  '- `testpilot doctor` — check project readiness and setup.',
  '- `testpilot explain <ruleId>` — learn why a rule matters and how to improve.',
  '',
  '## Honest limitations (do not overstate)',
  '',
  "- TestPilot's analysis is **static (Tier 1)**: it flags categories of problems and gives",
  '  category-level guidance. It does **not** inspect the DOM and does **not** produce exact,',
  '  DOM-derived locator replacements. Do not claim that it does.',
  '- There is no auto-fix, no AI-generated tests, and no locator repair.',
].join('\n')
