/**
 * The single canonical TestPilot + Playwright guidance. Every agent file derives
 * from this one source, so there is no duplicated wall of text to keep in sync.
 *
 * Built as a line array so fenced code blocks (which contain backticks) are easy
 * to include. Keep it honest: do not describe features that do not exist yet.
 */
export const CANONICAL_GUIDANCE = [
  '## What TestPilot QA is',
  '',
  'TestPilot QA is a developer-experience toolkit on top of Playwright. It does **not** replace',
  'Playwright and is **not** a custom test runner — Playwright runs the tests. Keep this project as',
  'plain, ejectable Playwright.',
  '',
  '## Project structure',
  '',
  '- `tests/ui/` — UI tests (use `page` and user-facing locators)',
  '- `tests/api/` — API tests (use the `request` fixture)',
  '- `playwright.config.ts` — Playwright config (parallelism, projects, reporter)',
  '- `testpilot.config.ts` — TestPilot config (`testDir`, `playwrightConfig`, rule severities)',
  '',
  '## Locator hierarchy (most → least preferred)',
  '',
  '1. `getByRole`, `getByLabel`, `getByPlaceholder`, `getByText`, `getByAltText`, `getByTitle`',
  '2. `getByTestId`',
  '3. Avoid raw CSS and `text=` engine strings',
  '4. Never use XPath, `:nth-child` / `.nth()`, class selectors, or deep `>` chains',
  '',
  '```ts',
  '// avoid',
  "page.locator('.btn-primary')",
  'page.locator(\'//button[@type="submit"]\')',
  '// prefer',
  "page.getByRole('button', { name: 'Save' })",
  "page.getByLabel('Email')",
  '```',
  '',
  '## Playwright best practices',
  '',
  '- Rely on Playwright auto-waiting; do **not** use `page.waitForTimeout()` (hard waits).',
  '- Use web-first assertions: `await expect(locator).toBeVisible()`, `toHaveText(...)`.',
  '- Keep tests independent and parallel-safe; avoid shared mutable state between tests.',
  '',
  '## API testing',
  '',
  '- Use the `request` fixture; assert `response.ok()` and the parsed body.',
  '- For offline examples, start a local `node:http` server inside the test.',
  '',
  '## Fixtures & Page Objects',
  '',
  '- Put reusable setup in Playwright fixtures; if the suite grows, put page interactions in Page',
  '  Objects (e.g. under `src/pages`).',
  '- Every test must be able to run on its own.',
  '',
  '## Use TestPilot',
  '',
  '- `testpilot analyze` — flag fragile locators and get a Locator Quality Score.',
  '- `testpilot doctor` — check project readiness and setup.',
  '- `testpilot explain <ruleId>` — learn why a rule matters and how to improve.',
  '',
  '## Honest limitations (do not overstate)',
  '',
  "- TestPilot's analysis is **static (Tier 1)**: it flags categories of problems and gives",
  '  category-level guidance. It does **not** inspect the DOM and does **not** produce exact,',
  '  DOM-derived locator replacements. Do not claim that it does.',
  '- There is no auto-fix, no AI-generated tests, and no locator repair.',
].join('\n')
