import { createHash } from 'node:crypto'

/**
 * Bumped when the generated guidance content changes meaningfully — drift is decided
 * by this version, so an unbumped change can never reach existing projects.
 * v2: agent globs follow the widened default `include` (JS/`*.e2e.ts` suites).
 * v3: `.mts`/`.cts` added to those globs.
 * v4: tag conventions — reuse the project's existing vocabulary, and how a subset is run.
 * v5: positional access and `locator('..')` are nudges, not prohibitions (Phase 11e/11f).
 */
export const GUIDANCE_VERSION = 5

const TOKEN = '@testpilot/guidance'
const MARKER_RE = /@testpilot\/guidance v(\d+) sha256:([0-9a-f]+)/

/** Short, deterministic content checksum (sha256, first 12 hex chars). */
export function hashGuidance(text: string): string {
  return createHash('sha256').update(text).digest('hex').slice(0, 12)
}

/** The generated-file marker line (an HTML comment, valid in every Markdown/MDC file). */
export function guidanceMarker(hash: string): string {
  return `<!-- ${TOKEN} v${GUIDANCE_VERSION} sha256:${hash} — generated by TestPilot QA. Do not hand-edit; update the canonical guidance and regenerate. -->`
}

export interface GuidanceMarker {
  version: number
  hash: string
}

/** Parses the marker from a generated file, or `null` if absent. */
export function parseGuidanceMarker(content: string): GuidanceMarker | null {
  const match = content.match(MARKER_RE)
  if (!match?.[1] || !match[2]) {
    return null
  }
  return { version: Number(match[1]), hash: match[2] }
}

/** Returns the file body with the marker line removed (the bytes the hash covers). */
export function extractGeneratedBody(content: string): string {
  return content.replace(/^.*@testpilot\/guidance.*\r?\n/m, '')
}

/**
 * True when the content was generated by TestPilot and has not been hand-edited
 * (its body still hashes to the value in its marker). Exported so Milestone 5B's
 * `doctor` drift detection can distinguish pristine vs. user-edited files.
 */
export function isGuidancePristine(content: string): boolean {
  const marker = parseGuidanceMarker(content)
  if (!marker) {
    return false
  }
  return hashGuidance(extractGeneratedBody(content)) === marker.hash
}
