import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { generateAgentFiles, hashGuidance } from '@testpilot/ai'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { buildProgram } from '../src/program.js'

let dir: string

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'testpilot-add-ai-'))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

const claudeGenerated = generateAgentFiles(['claude'])[0]?.content ?? ''

/** A pristine-but-old-version CLAUDE.md (parses, hashes clean, version 0 → stale). */
function staleClaude(): string {
  const body = '# CLAUDE.md\n\nold generated body\n'
  const marker = `<!-- @testpilot/guidance v0 sha256:${hashGuidance(body)} — generated by TestPilot QA. -->`
  return `${marker}\n${body}`
}

async function runAddAi(args: string[] = [], globals: string[] = []) {
  const logs: string[] = []
  const errs: string[] = []
  let exitCode: number | undefined
  const logSpy = vi.spyOn(console, 'log').mockImplementation((...a: unknown[]) => {
    logs.push(a.map(String).join(' '))
  })
  const errSpy = vi.spyOn(console, 'error').mockImplementation((...a: unknown[]) => {
    errs.push(a.map(String).join(' '))
  })
  const exitSpy = vi.spyOn(process, 'exit').mockImplementation(((code?: number) => {
    exitCode = code
    throw new Error('__exit__')
  }) as never)
  try {
    await buildProgram().parseAsync([
      'node',
      'testpilot',
      '--cwd',
      dir,
      ...globals,
      'add',
      'ai',
      ...args,
    ])
  } catch (error) {
    if (!(error instanceof Error) || error.message !== '__exit__') throw error
  } finally {
    logSpy.mockRestore()
    errSpy.mockRestore()
    exitSpy.mockRestore()
  }
  return { stdout: logs.join('\n'), stderr: errs.join('\n'), exitCode }
}

describe('add ai — dry run (default)', () => {
  it('reports what would be created without writing anything', async () => {
    const { stdout, exitCode } = await runAddAi()
    expect(exitCode).toBeUndefined()
    expect(stdout).toContain('would create')
    expect(stdout).toContain('Re-run with --write')
    expect(existsSync(join(dir, 'CLAUDE.md'))).toBe(false)
  })
})

describe('add ai --write', () => {
  it('creates the guidance files, then reports them current on a second run', async () => {
    await runAddAi(['--write'])
    expect(existsSync(join(dir, 'CLAUDE.md'))).toBe(true)
    expect(existsSync(join(dir, 'AGENTS.md'))).toBe(true)
    expect(readFileSync(join(dir, 'CLAUDE.md'), 'utf8')).toContain('@testpilot/guidance')

    const second = await runAddAi()
    expect(second.stdout).toContain('current')
    expect(second.stdout).toContain('up to date')
  })

  it('writes only the selected agent', async () => {
    await runAddAi(['claude', '--write'])
    expect(existsSync(join(dir, 'CLAUDE.md'))).toBe(true)
    expect(existsSync(join(dir, 'AGENTS.md'))).toBe(false)
  })

  it('updates a stale generated file', async () => {
    writeFileSync(join(dir, 'CLAUDE.md'), staleClaude())
    const preview = await runAddAi(['claude'])
    expect(preview.stdout).toContain('would update')

    await runAddAi(['claude', '--write'])
    // Now it matches the current generator output.
    expect(readFileSync(join(dir, 'CLAUDE.md'), 'utf8')).toBe(claudeGenerated)
  })
})

describe('add ai — protecting user edits', () => {
  it('does not overwrite an edited file without --force', async () => {
    const edited = `${claudeGenerated}\n<!-- my hand edits -->\n`
    writeFileSync(join(dir, 'CLAUDE.md'), edited)
    const { stdout } = await runAddAi(['claude', '--write'])
    expect(stdout).toContain('edited')
    expect(stdout).toContain('--force')
    expect(readFileSync(join(dir, 'CLAUDE.md'), 'utf8')).toBe(edited) // untouched
  })

  it('overwrites an edited file with --force', async () => {
    writeFileSync(join(dir, 'CLAUDE.md'), `${claudeGenerated}\n<!-- my hand edits -->\n`)
    await runAddAi(['claude', '--force'])
    expect(readFileSync(join(dir, 'CLAUDE.md'), 'utf8')).toBe(claudeGenerated)
  })
})

describe('add ai — output modes & errors', () => {
  it('rejects an unknown agent (exit 2)', async () => {
    const { exitCode, stderr } = await runAddAi(['bogus'])
    expect(exitCode).toBe(2)
    expect(stderr).toContain('Unknown agent')
  })

  it('emits a stable JSON report', async () => {
    const { stdout } = await runAddAi(['claude'], ['--json'])
    const report = JSON.parse(stdout)
    expect(report).toMatchObject({ command: 'add', resource: 'ai', dryRun: true })
    expect(report.files[0]).toMatchObject({ agent: 'claude', action: 'create' })
    expect(report.summary.created).toBe(1)
  })

  it('prints nothing with --quiet', async () => {
    const { stdout } = await runAddAi(['claude'], ['--quiet'])
    expect(stdout).toBe('')
  })
})
