import type { AnalysisReport, Finding, ScoreBreakdown } from '@testpilot/core'
import { CLI_VERSION } from '../version.js'

/**
 * Renders an analysis report as a single self-contained HTML document — inline
 * CSS, no external assets, no scripts, no network or tracking. Pure: same input,
 * same bytes. A shareable, scannable view of the *full* report (unlike the
 * gate-facing `table`/`sarif` outputs, it is not scoped to new findings under a
 * baseline); when a baseline was used it shows the comparison summary too.
 */
export function toHtml(report: AnalysisReport): string {
  const { summary, score, findings, warnings, parseErrors, baseline } = report
  const title = 'TestPilot QA — Locator Quality Report'

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${esc(title)}</title>`,
    `<style>${STYLES}</style>`,
    '</head>',
    '<body>',
    '<main>',
    `<h1>${esc(title)}</h1>`,
    `<p class="lede">Static <strong>Tier&nbsp;1</strong> locator analysis — deterministic and offline. Category-level guidance only; <strong>no DOM-aware suggestions, no automatic rewrites</strong>.</p>`,
    scoreCard(score, report.summary),
    summarySection(summary, baseline),
    helperSection(report),
    discoverySection(report),
    warningsSection(warnings),
    findingsSection(findings),
    parseErrorsSection(parseErrors),
    `<footer>Generated by TestPilot QA v${esc(CLI_VERSION)} — static Tier 1 analysis. Findings are heuristic; they are not DOM-verified facts.</footer>`,
    '</main>',
    '</body>',
    '</html>',
    '',
  ].join('\n')
}

/** Escapes text for safe interpolation into HTML element/attribute content. */
function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function gradeClass(grade: string): string {
  return `grade-${/^[A-F]$/.test(grade) ? grade : 'NA'}`
}

function scoreCard(score: AnalysisReport['score'], summary: AnalysisReport['summary']): string {
  const subs: Array<[string, ScoreBreakdown]> = [
    ['Resilience', score.subScores.resilience],
    ['Accessibility', score.subScores.accessibility],
    ['Maintainability', score.subScores.maintainability],
    ['Flakiness', score.subScores.flakiness],
  ]
  const rows = subs
    .map(([label, s]) => {
      const bar = `<span class="bar"><span class="bar-fill ${gradeClass(s.grade)}" style="width:${clampPct(s.score)}%"></span></span>`
      const value = `<span class="sub-score">${s.score} <span class="badge ${gradeClass(s.grade)}">${esc(s.grade)}</span></span>`
      return `<li><span class="sub-label">${esc(label)}</span>${bar}${value}</li>`
    })
    .join('')
  return [
    '<section class="score-card">',
    `<div class="headline ${gradeClass(score.grade)}">`,
    `<div class="score-number">${score.score}</div>`,
    `<div class="score-grade">Grade ${esc(score.grade)}</div>`,
    `<div class="score-meta">Locator Quality Score · ${score.callSites} call-site(s)</div>`,
    '</div>',
    `<ul class="subscores">${rows}</ul>`,
    // The shared artifact must not show a clean sub-score bar above a findings
    // list those very findings are in. Naming the exclusion here is the whole
    // point of counting it.
    unscoredNote(summary),
    '</section>',
  ]
    .filter((part) => part !== '')
    .join('\n')
}

/** Names findings counted but excluded from the score, or '' when there are none. */
function unscoredNote(summary: AnalysisReport['summary']): string {
  const unscored = summary.unscoredFindings ?? 0
  if (unscored === 0) {
    return ''
  }
  const rules = summary.unscoredRuleIds ?? []
  const from = rules.length > 0 ? ` (${esc(rules.join(', '))})` : ''
  return `<p class="unscored"><strong>${unscored}</strong> finding(s)${from} are counted but <strong>not scored</strong> — they are measured per test, while the score is per locator call-site. The sub-scores above do not reflect them.</p>`
}

function summarySection(
  summary: AnalysisReport['summary'],
  baseline: AnalysisReport['baseline'],
): string {
  const { error, warn, info } = summary.bySeverity
  const cards = [
    statCard(String(summary.filesAnalyzed), 'files analyzed'),
    statCard(String(summary.findings), 'findings'),
    statCard(String(error), 'error', 'sev-error'),
    statCard(String(warn), 'warn', 'sev-warn'),
    statCard(String(info), 'info', 'sev-info'),
  ].join('')
  const previousId = baseline?.matchedByPreviousId
    ? ` ${baseline.matchedByPreviousId} of those matched under a rule's previous id — that rule was split or renamed since this baseline was recorded.`
    : ''
  const baselineNote = baseline
    ? `<p class="baseline">Baseline <code>${esc(baseline.path)}</code>: <strong>${baseline.newFindings}</strong> new finding(s), ${baseline.baselinedFindings} already baselined.${previousId}</p>`
    : ''
  return `<section class="summary"><div class="stats">${cards}</div>${baselineNote}</section>`
}

function statCard(value: string, label: string, cls = ''): string {
  return `<div class="stat ${cls}"><div class="stat-value">${esc(value)}</div><div class="stat-label">${esc(label)}</div></div>`
}

/** Says when the report covers files Playwright does not run. */
function helperSection(report: AnalysisReport): string {
  const count = report.summary?.helperFiles ?? 0
  if (count === 0) return ''
  return `<section class="helpers"><p>Includes ${count} page object/helper file(s), which Playwright does not run — their findings are marked <code>helper</code>.</p></section>`
}

/** Names the directories scanned and who chose them, when it was not the user. */
function discoverySection(report: AnalysisReport): string {
  const discovery = report.discovery
  if (!discovery?.playwrightConfigPath) return ''
  return `<section class="discovery"><p>Scanned ${esc(discovery.roots.join(', '))} — test directory taken from ${esc(discovery.playwrightConfigPath)}.</p></section>`
}

function warningsSection(warnings: AnalysisReport['warnings']): string {
  if (warnings.length === 0) return ''
  const items = warnings.map((w) => `<li>${esc(w.message)}</li>`).join('')
  return `<section class="warnings"><h2>Warnings</h2><ul>${items}</ul></section>`
}

function findingsSection(findings: Finding[]): string {
  if (findings.length === 0) {
    return '<section class="findings"><h2>Findings</h2><p class="clean">No locator issues found. ✔</p></section>'
  }
  // Group by file, preserving first-seen order.
  const byFile = new Map<string, Finding[]>()
  for (const finding of findings) {
    const list = byFile.get(finding.file)
    if (list) list.push(finding)
    else byFile.set(finding.file, [finding])
  }
  const groups = [...byFile.entries()]
    .map(([file, group]) => {
      const rows = group.map(findingRow).join('')
      return `<details open class="file-group"><summary><span class="file">${esc(file)}</span><span class="count">${group.length}</span></summary><div class="rows">${rows}</div></details>`
    })
    .join('')
  return `<section class="findings"><h2>Findings (${findings.length})</h2>${groups}</section>`
}

/** Only link http(s) URLs — never `javascript:`/`data:` — even though `esc()`
 * already blocks attribute breakout. Defense-in-depth for the one URL sink. */
function isHttpUrl(url: string): boolean {
  return /^https?:\/\//i.test(url)
}

function findingRow(finding: Finding): string {
  // The helper section above claims these are marked; mark them.
  const scope = finding.inHelper ? '<span class="badge-helper">helper</span> ' : ''
  const sev = finding.severity
  const rule = isHttpUrl(finding.docsUrl)
    ? `<a href="${esc(finding.docsUrl)}" rel="noreferrer noopener">${esc(finding.ruleId)}</a>`
    : esc(finding.ruleId)
  const suggestion = finding.suggestion
    ? `<p class="suggestion">${esc(finding.suggestion)}</p>`
    : ''
  return [
    '<div class="finding">',
    `<div class="finding-head"><span class="badge sev-${esc(sev)}">${esc(sev)}</span>${scope}`,
    `<span class="rule">${rule}</span>`,
    `<span class="loc">${esc(finding.file)}:${finding.line}:${finding.column}</span></div>`,
    `<p class="message">${esc(finding.message)}</p>`,
    `<pre class="snippet"><code>${esc(finding.snippet)}</code></pre>`,
    suggestion,
    '</div>',
  ].join('')
}

function parseErrorsSection(parseErrors: AnalysisReport['parseErrors']): string {
  if (parseErrors.length === 0) return ''
  const items = parseErrors
    .map((p) => `<li><code>${esc(p.file)}</code> — ${esc(p.message)}</li>`)
    .join('')
  return `<section class="parse-errors"><h2>Could not parse (${parseErrors.length})</h2><ul>${items}</ul></section>`
}

function clampPct(score: number): number {
  return Math.max(0, Math.min(100, Math.round(score)))
}

const STYLES = `
:root{--bg:#0f1115;--card:#171a21;--ink:#e6e8eb;--muted:#9aa3ad;--line:#272b33;
--a:#3fb950;--b:#56a8ff;--c:#d29922;--d:#e8843c;--f:#f85149;--na:#8b949e}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
main{max-width:880px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:22px;margin:0 0 4px}h2{font-size:16px;margin:28px 0 12px;color:var(--muted);
text-transform:uppercase;letter-spacing:.04em}
.lede{color:var(--muted);margin:0 0 24px}
a{color:var(--b)}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.score-card{display:flex;gap:24px;flex-wrap:wrap;align-items:center;background:var(--card);
border:1px solid var(--line);border-radius:12px;padding:20px}
.headline{min-width:160px}.score-number{font-size:54px;font-weight:700;line-height:1}
.score-grade{font-weight:600}.score-meta{color:var(--muted);font-size:13px;margin-top:4px}
.subscores{flex:1;min-width:260px;list-style:none;margin:0;padding:0}
.subscores li{display:grid;grid-template-columns:120px 1fr 64px;gap:10px;align-items:center;margin:6px 0}
.sub-label{color:var(--muted)}.bar{height:8px;background:#0b0d11;border-radius:6px;overflow:hidden}
.bar-fill{display:block;height:100%}.sub-score{text-align:right;font-variant-numeric:tabular-nums}
.stats{display:flex;gap:12px;flex-wrap:wrap}
.stat{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 16px;min-width:96px}
.stat-value{font-size:24px;font-weight:700}.stat-label{color:var(--muted);font-size:13px}
.baseline{color:var(--muted);margin:12px 0 0}
.unscored{color:var(--muted);margin:14px 0 0;font-size:13px;line-height:1.5}
.badge{display:inline-block;padding:1px 8px;border-radius:999px;font-size:12px;font-weight:700;color:#0b0d11}
.grade-A,.bar-fill.grade-A{background:var(--a)}.grade-B,.bar-fill.grade-B{background:var(--b)}
.grade-C,.bar-fill.grade-C{background:var(--c)}.grade-D,.bar-fill.grade-D{background:var(--d)}
.grade-F,.bar-fill.grade-F{background:var(--f)}.grade-NA{background:var(--na)}
.sev-error{background:var(--f);color:#fff}.sev-warn{background:var(--c);color:#0b0d11}
.sev-info{background:var(--b);color:#0b0d11}
.stat.sev-error .stat-value{color:var(--f)}.stat.sev-warn .stat-value{color:var(--c)}
.file-group{background:var(--card);border:1px solid var(--line);border-radius:10px;margin:10px 0;overflow:hidden}
.file-group>summary{cursor:pointer;padding:10px 14px;display:flex;justify-content:space-between;align-items:center;font-weight:600}
.file-group .count{color:var(--muted);font-weight:400}
.rows{border-top:1px solid var(--line)}
.finding{padding:14px;border-bottom:1px solid var(--line)}.finding:last-child{border-bottom:0}
.finding-head{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.rule{font-weight:600}.loc{color:var(--muted);font-size:13px;margin-left:auto}
.message{margin:8px 0}.snippet{background:#0b0d11;border:1px solid var(--line);border-radius:8px;
padding:10px 12px;overflow:auto;margin:8px 0 0}.snippet code{color:#e6edf3}
.suggestion{color:var(--muted);margin:8px 0 0}.suggestion::before{content:"→ "}
.badge-helper{background:#e5e7eb;color:#374151;border-radius:4px;padding:1px 6px;font-size:11px;margin-right:6px}
.clean{color:var(--a)}.warnings li,.parse-errors li{margin:4px 0}
footer{margin-top:40px;color:var(--muted);font-size:13px;border-top:1px solid var(--line);padding-top:16px}
`.trim()
